apiVersion: v1
kind: Pod
metadata:
  annotations:
    kyverno.io/verify-images: '{"172.20.0.3:5000/ledger-api@sha256:7a0a6e625908ce67fada5476551e95d8f8b36f659d02b5d10b4f1eaafb2c5c5d":"pass"}'
  creationTimestamp: "2026-07-08T13:34:01Z"
  generation: 1
  labels:
    run: test-signed
  name: test-signed
  namespace: payments
  resourceVersion: "54112"
  uid: 12adfbd1-b3ab-408f-b350-5b9fdc9f0d1f
spec:
  containers:
  - image: 172.20.0.3:5000/ledger-api:insecure@sha256:7a0a6e625908ce67fada5476551e95d8f8b36f659d02b5d10b4f1eaafb2c5c5d
    imagePullPolicy: IfNotPresent
    name: test-signed
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pmr6g
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: dodo-ledger-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-pmr6g
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-08T13:34:01Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-08T13:34:01Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-08T13:34:01Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-08T13:34:01Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-08T13:34:01Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://79e200fcb474b8b9b3f257896fb24d0f7a6ae4e6b96b77f11667dad7c9004069
    image: 172.20.0.3:5000/ledger-api:insecure
    imageID: 172.20.0.3:5000/ledger-api@sha256:7a0a6e625908ce67fada5476551e95d8f8b36f659d02b5d10b4f1eaafb2c5c5d
    lastState: {}
    name: test-signed
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-08T13:34:01Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pmr6g
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.20.0.2
  hostIPs:
  - ip: 172.20.0.2
  observedGeneration: 1
  phase: Running
  podIP: 10.244.0.15
  podIPs:
  - ip: 10.244.0.15
  qosClass: BestEffort
  resources: {}
  startTime: "2026-07-08T13:34:01Z"
