apiVersion: v1
data:
  db-password: UEBzc3cwcmQxMjM=
  stripe-api-key: c2tfbGl2ZV85ZjNhMmI3YzFlNGQ4UkVEQUNURUQ=
kind: Secret
metadata:
  creationTimestamp: "2026-07-08T08:26:46Z"
  name: ledger-api-secrets
  namespace: payments
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: ledger-api-secrets
    uid: 18825992-12c8-49f2-be29-de0d03851bed
  resourceVersion: "6955"
  uid: 5f99ab27-58bc-445e-88a3-6960e9b9d493
type: Opaque
