apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-07-08T07:36:36Z"
    generateName: ledger-api-77745f4d76-
    generation: 1
    labels:
      app: ledger-api
      pod-template-hash: 77745f4d76
    name: ledger-api-77745f4d76-5vgf5
    namespace: payments
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: ledger-api-77745f4d76
      uid: 645032d6-3913-48f1-93bd-ecf95e85c136
    resourceVersion: "2673"
    uid: 8293dd7d-6e48-4c75-8214-f5dbb1cd312e
  spec:
    automountServiceAccountToken: false
    containers:
    - env:
      - name: PYTHONDONTWRITEBYTECODE
        value: "1"
      - name: STRIPE_API_KEY
        valueFrom:
          secretKeyRef:
            key: stripe-api-key
            name: ledger-api-secrets
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: db-password
            name: ledger-api-secrets
      image: ledger-api:insecure
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: ledger-api
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: dodo-ledger-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    serviceAccount: ledger-api
    serviceAccountName: ledger-api
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir: {}
      name: tmp
  status:
    allocatedResources:
      cpu: 50m
      memory: 64Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:36Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:36Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:42Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:42Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:36Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 50m
        memory: 64Mi
      containerID: containerd://082309374827d3dc476e4971c6b6bd54426bd2063a8907ade4aada05acad0481
      image: docker.io/library/ledger-api:insecure
      imageID: docker.io/library/import-2026-07-08@sha256:db54f18ac1c2e0c8a048e139e08ce86112dd8cd52ff39ab05b555cbbd57034c9
      lastState: {}
      name: ledger-api
      ready: true
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-07-08T07:36:36Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    hostIP: 172.20.0.2
    hostIPs:
    - ip: 172.20.0.2
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.10
    podIPs:
    - ip: 10.244.0.10
    qosClass: Burstable
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 28m
        memory: 64Mi
    startTime: "2026-07-08T07:36:36Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-07-08T07:36:30Z"
    generateName: ledger-api-77745f4d76-
    generation: 1
    labels:
      app: ledger-api
      pod-template-hash: 77745f4d76
    name: ledger-api-77745f4d76-9wgd4
    namespace: payments
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: ledger-api-77745f4d76
      uid: 645032d6-3913-48f1-93bd-ecf95e85c136
    resourceVersion: "2630"
    uid: a83213a8-7307-42cd-95ca-5cde129bce20
  spec:
    automountServiceAccountToken: false
    containers:
    - env:
      - name: PYTHONDONTWRITEBYTECODE
        value: "1"
      - name: STRIPE_API_KEY
        valueFrom:
          secretKeyRef:
            key: stripe-api-key
            name: ledger-api-secrets
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: db-password
            name: ledger-api-secrets
      image: ledger-api:insecure
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: ledger-api
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: dodo-ledger-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    serviceAccount: ledger-api
    serviceAccountName: ledger-api
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir: {}
      name: tmp
  status:
    allocatedResources:
      cpu: 50m
      memory: 64Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:30Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:30Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:36Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:36Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:30Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 50m
        memory: 64Mi
      containerID: containerd://12c34795c527cc1fd3c88890482dc2d4c70dde2b9f39df07835bf1eda4824d26
      image: docker.io/library/ledger-api:insecure
      imageID: docker.io/library/import-2026-07-08@sha256:db54f18ac1c2e0c8a048e139e08ce86112dd8cd52ff39ab05b555cbbd57034c9
      lastState: {}
      name: ledger-api
      ready: true
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-07-08T07:36:30Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    hostIP: 172.20.0.2
    hostIPs:
    - ip: 172.20.0.2
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.9
    podIPs:
    - ip: 10.244.0.9
    qosClass: Burstable
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 28m
        memory: 64Mi
    startTime: "2026-07-08T07:36:30Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-07-08T07:36:42Z"
    generateName: ledger-api-77745f4d76-
    generation: 1
    labels:
      app: ledger-api
      pod-template-hash: 77745f4d76
    name: ledger-api-77745f4d76-dx2wp
    namespace: payments
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: ledger-api-77745f4d76
      uid: 645032d6-3913-48f1-93bd-ecf95e85c136
    resourceVersion: "2716"
    uid: ed68bf6d-a496-4aa7-a9bf-61f9ed4272bf
  spec:
    automountServiceAccountToken: false
    containers:
    - env:
      - name: PYTHONDONTWRITEBYTECODE
        value: "1"
      - name: STRIPE_API_KEY
        valueFrom:
          secretKeyRef:
            key: stripe-api-key
            name: ledger-api-secrets
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: db-password
            name: ledger-api-secrets
      image: ledger-api:insecure
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: ledger-api
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: dodo-ledger-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    serviceAccount: ledger-api
    serviceAccountName: ledger-api
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - emptyDir: {}
      name: tmp
  status:
    allocatedResources:
      cpu: 50m
      memory: 64Mi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:42Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:42Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:48Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:48Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-07-08T07:36:42Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 50m
        memory: 64Mi
      containerID: containerd://053c4945d3d810631c5f5eb531baf59a546fdc0f6e273f03d24bd3129de8a4af
      image: docker.io/library/ledger-api:insecure
      imageID: docker.io/library/import-2026-07-08@sha256:db54f18ac1c2e0c8a048e139e08ce86112dd8cd52ff39ab05b555cbbd57034c9
      lastState: {}
      name: ledger-api
      ready: true
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-07-08T07:36:43Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    hostIP: 172.20.0.2
    hostIPs:
    - ip: 172.20.0.2
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.11
    podIPs:
    - ip: 10.244.0.11
    qosClass: Burstable
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 28m
        memory: 64Mi
    startTime: "2026-07-08T07:36:42Z"
kind: List
metadata:
  resourceVersion: ""
