---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    db-password: AgAg2KzTWxf/eosWSTnANphUYMmSQ/qsmXLRqdy2RmvPcAAXb6SUX/alTpXLi+A9k5SiXhzs5hJLUVv+C1WiEdqampHSSnxps7ZQVFY8VJrdEC5L7NpBbiAMLvAV/1W8dd/uoa5xfQbjKNGw9fVvt4liBkWWcy/ksMRsVjvQt3zR5v6YO9NFt/bAvtU+ZPBbI+SWK4tUap7wjk3zB+XosAAj84+Cr8beEtXMR2dLtT1lzs/Isv9pHHl4h/3kRDKkpLSlSg0tMjUzhBrRFp1paFznGMZZJXqKt0kQLhlUjtapH8RTz8sulVrZw4dybfQRWfppaJOa2fPP/tXkHfjzMkt8UyGukw6/9RA4j2qbAHSDLrppnJVWiRvEfBQG/fCwoyYAI167WbzjWwho2e2ORd/9zm4U7DVZyhu2jl8RyJTStYDxntNzsVeC2dViu+MbocZM8CrbAXJAybFrYsLwAe0AZ6+vdIDlzW4V9d06Ea+9gokjykc5F3rLFw+RO7GLncGS9Xdzj3R4QY5bYaKosn0yJM6nNcFCdwyt0LRIUrT1HufixYpoUFJdWvNlIdMMgViOFvYdC4YlzXBAadIdXumP4xBmuffN5zQQ6ST7Z9uCsCWUEgUvjZKvjbOOaXkdKTq6/z2GKq2ne4icBpm6jtS+LA6daHdygcibht5g4ojYVRZgBnJHoD9++7LJ0H7EffSwG67J7Iyy1tnuzA==
    stripe-api-key: AgCY3OSI0R18rvs7nUaPapNhssXiSOdM0S5LeYhWoQ5Y9M2M4eiDZmU0sJSh12EYvXbzQt9nuiYbwNTpQkYo0Uw5ZW/T6gDkidhmIG8Uvn9qRAk8EiI1ymoBKy/JU+lP9gpAO3FGjYZF0p0Nh5NffpupmbBSZPIyWvf68DsyawbMCTz8+dJfWi2cZ9juoQwxGvgnpVetxvCk6Fwos34V2hLKnCEbkxztW2kZA4V00sk21HVnU13tX9awGTll/C5TKscNe2QXZ+Iwg7GpZyZykXiwC+70tX1bnCn4oRTGljP6ZXZ1igmvPk2X+c6Q96T3cUWhb+/0vXPRXctnSj+jSnUSe1OZHnJccWMb2Yo/6sicxs1UCIj+zgmf+68pe/xOBtsHbfqQwteLuROWTnNZjSoqdokVLrMWi0FiWJ+9Cs2ofGWw1pSunj+mq3A3ONsPMAwZysskFBNCCTQCky6H5HO29iAlcqOoXjHaY9MC0+nhIuMPxbETVmDxmOYFfOTWp9jf0xx1o3+jWDeV63jlJWgWO1Ecfeac3i2Ex1ZH4y/esRbQfcx7X0oYMdQrhIoxsOdrxxVgwHf2PZ9renN59yey+7+aSRtKx6Rq2uzZ/oi9dZ+0aPkBXxxnm23dD4rkEzxGBB8U6RjO3ppBdAS5ZDyCcZUmgaIawWCvt0Idm0QaffTFKV6bAVP8b2oxhxLMjtq9RtzblUOhipY6K6w2iU0NVNu2t5vBmGxxj4rWhg==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
    type: Opaque
